export const restaurantState = {
    location: "",
    description: "",
    descriptionGeo: "",
    cupeQuantity: 0,
    tableQuantity:0,
    terraceQuantity:0,
    hallStart:'',
    hallEnd:'',
    kitchenStart: '',
    kitchenEnd:'',
    is24:false,
    is24Hall:false,
    musicStart: '',
    musicEnd : '',
    corporative: false,
    doubleSecurity: false,
    lat:'',
    lng:'',
    parent: false,
    adressGeorgian:'',
    adressEnglish:'',
    isCupe:false,
    isTerace:false,
    priceID:1,
    restaurantTypeId:1,
    restaurantRegionId:1

    // image1: null,
    // image2: null,
    // image3: null,

}